//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WorldCameraAngularVelocityDamp {
            get {
                return ((float)(this["WorldCameraAngularVelocityDamp"]));
            }
            set {
                this["WorldCameraAngularVelocityDamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WorldCameraZoomVelocityDamp {
            get {
                return ((float)(this["WorldCameraZoomVelocityDamp"]));
            }
            set {
                this["WorldCameraZoomVelocityDamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public float WorldCameraRotationInputMultiplier {
            get {
                return ((float)(this["WorldCameraRotationInputMultiplier"]));
            }
            set {
                this["WorldCameraRotationInputMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WorldCameraZoomInputMultiplier {
            get {
                return ((float)(this["WorldCameraZoomInputMultiplier"]));
            }
            set {
                this["WorldCameraZoomInputMultiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.7")]
        public float WorldCameraZoomMax {
            get {
                return ((float)(this["WorldCameraZoomMax"]));
            }
            set {
                this["WorldCameraZoomMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public float WorldCameraZoomMinRelative {
            get {
                return ((float)(this["WorldCameraZoomMinRelative"]));
            }
            set {
                this["WorldCameraZoomMinRelative"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WorldCameraAngularVelocityMax {
            get {
                return ((float)(this["WorldCameraAngularVelocityMax"]));
            }
            set {
                this["WorldCameraAngularVelocityMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float WorldCameraZoomVelocityMax {
            get {
                return ((float)(this["WorldCameraZoomVelocityMax"]));
            }
            set {
                this["WorldCameraZoomVelocityMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public float WorldRadius {
            get {
                return ((float)(this["WorldRadius"]));
            }
            set {
                this["WorldRadius"] = value;
            }
        }
    }
}
